# -*- coding: utf-8 -*-
"""Ai travel agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0oJHFAQKGwGsuGfs7mmSghGDwnXuWjh

#Key Components

1. **StateGraph**: The core of our application, defining the flow of our Travel Planner.
2. **PlannerState**: A custom type representing the state of our planning process.
3. **Node Functions**: Individual steps in our planning process (input_city, input_interests,
create_itinerary).
4. **LLM Integration**: Utilizing a language model to generate the final itinerary.
"""

!pip install langchain langchain_core langchain_groq langchain_community langchain langgraph

import os
from typing import TypedDict, Annotated, List
from langgraph.graph import StateGraph, END
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables.graph import MermaidDrawMethod
from IPython.display import display, Image

"""##Define Agent  --> State"""

class PlannerState(TypedDict):
   messages : Annotated[List[HumanMessage | AIMessage], "the messages in the conversation"]
   city: str
   interests: List[str]
   itinerary: str

from langchain_groq import ChatGroq
llm = ChatGroq(
temperature = 0,
groq_api_key = "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",
model_name = "llama-3.3-70b-versatile"
)
result = llm.invoke("What is Multi AI Agent")
result.content

itinerary_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful travel assistant. Create a day trip itinerary for {city} based on the user's interests: {interests}. Provide a brief, bulleted itinerary."),
    ("human", "Create an itinerary for my day trip."),
])

"""##Define Agent Function"""

def input_city(state: PlannerState) -> PlannerState:
    print("Please enter the city you want to visit for your day trip:")
    user_message = input("Your Input: ")

    return {
        **state,
        "city": user_message,
        "messages": state["messages"] + [HumanMessage(content=user_message)]
    }


def input_interest(state: PlannerState) -> PlannerState:
    print(
        f"Please enter your interests for the trip to {state['city']} (comma-separated):"
    )
    user_message = input("Your Input: ")

    return {
        **state,
        "interests": [interest.strip() for interest in user_message.split(",")],
        "messages": state["messages"] + [HumanMessage(content=user_message)]
    }


def create_itinerary(state: PlannerState) -> PlannerState:
    print(
        f"Creating an itinerary for {state['city']} based on interests: "
        f"{', '.join(state['interests'])}..."
    )

    response = llm.invoke(
        itinerary_prompt.format_prompt(
            city=state["city"],
            interests=state["interests"]
        ).to_messages()
    )

    print("\nFinal Itinerary:")
    print(response.content)

    return {
        **state,
        "messages": state["messages"] + [AIMessage(content=response.content)],
        "itinerary": response.content,
    }

"""##Create and Compile the Graph"""

workflow = StateGraph(PlannerState)

workflow.add_node("input_city", input_city)
workflow.add_node("input_interest", input_interest)
workflow.add_node("create_itinerary", create_itinerary)

workflow.set_entry_point("input_city")

workflow.add_edge("input_city", "input_interest")
workflow. add_edge("input_interest", "create_itinerary")
workflow.add_edge("create_itinerary", END)

app = workflow. compile()

"""##Display Graph Sructure"""

display(
Image(
app.get_graph().draw_mermaid_png(
draw_method = MermaidDrawMethod.API
)
)
)

"""##Define the fuunction that runs graph"""

def travel_planner(user_request: str):
    print(f"Initial Request: {user_request}\n")

    state = {
        "messages": [HumanMessage(content=user_request)],
        "city": "",
        "interests": [],
        "itinerary": ""
    }

    for output in app.stream(state):
        pass

user_request = "I want to plan a day trip"
travel_planner(user_request)

!pip install gradio

import gradio as gr
from typing import TypedDict, List
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq import ChatGroq

# -----------------------------
# LLM Configuration
# -----------------------------
llm = ChatGroq(
    temperature=0,
    model_name="llama-3.3-70b-versatile",
groq_api_key = "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",
)

# -----------------------------
# Prompt
# -----------------------------
itinerary_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        "You are a professional travel planner. Create a stylish one-day itinerary for {city} "
        "based on these interests: {interests}. Use emojis and bullet points."
    ),
    ("human", "Create my itinerary.")
])

# -----------------------------
# Logic
# -----------------------------
def create_itinerary(city: str, interests: str) -> str:
    interests_list = [i.strip() for i in interests.split(",")]
    response = llm.invoke(
        itinerary_prompt.format_prompt(
            city=city,
            interests=interests_list
        ).to_messages()
    )
    return response.content

# -----------------------------
# Custom CSS
# -----------------------------
custom_css = """
body {
    background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
}

.gradio-container {
    font-family: 'Inter', sans-serif;
}

.hero-title {
    font-size: 42px;
    font-weight: 800;
    text-align: center;
    color: white;
}

.hero-subtitle {
    text-align: center;
    font-size: 18px;
    color: #cbd5e1;
    margin-bottom: 30px;
}

.card {
    background: #111827;
    border-radius: 16px;
    padding: 24px;
    box-shadow: 0 20px 40px rgba(0,0,0,0.4);
}

textarea, input {
    background-color: #020617 !important;
    color: white !important;
    border-radius: 12px !important;
}

button {
    background: linear-gradient(90deg, #f97316, #fb923c) !important;
    border-radius: 14px !important;
    font-weight: 600 !important;
    font-size: 16px !important;
}

button:hover {
    transform: scale(1.03);
}
"""

# -----------------------------
# Gradio UI (PRO)
# -----------------------------
with gr.Blocks(css=custom_css) as demo:

    gr.Markdown(
        """
        <div class="hero-title">✈️Travelia AI</div>
        <div class="hero-subtitle">
            Design your perfect day trip with AI-powered planning
        </div>
        """
    )

    with gr.Row():
        with gr.Column(scale=1):
            with gr.Group(elem_classes="card"):
                city = gr.Textbox(
                    label="📍 Destination City",
                    placeholder="e.g. Jaipur, Paris, Tokyo"
                )

                interests = gr.Textbox(
                    label="🎯 Interests",
                    placeholder="e.g. Forts, Food, Culture, Shopping"
                )

                submit = gr.Button("✨ Generate Itinerary")

        with gr.Column(scale=1):
            with gr.Group(elem_classes="card"):
                output = gr.Textbox(
                    label="🗺️ Your Personalized Itinerary",
                    lines=14
                )

    submit.click(
        fn=create_itinerary,
        inputs=[city, interests],
        outputs=output
    )

demo.launch()

